name: marvel_api
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  dartz: ^0.10.1
  flutter_svg: ^2.0.7
  dio: ^5.3.0
  equatable: ^2.0.5
  yaml: ^3.1.2
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/utils/resources/icons/
    - lib/config/
